version: '3.1'
services:
  app:
    container_name: app-user
    image: app-user
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      - rabbitmq-container
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"